#include<process.h>
#include<stdlib.h>
#include<stdio.h>
#include<dos.h>
#include<conio.h>
#include<bios.h>
#define Node struct node

Node
{char nData;
 Node *strpNext;
 Node *strpPre;
 };

extern char *name;
extern Node *strpFirst=NULL;
extern Node *strpRear=NULL;
extern Node *strpNow=NULL;
extern Node *CreatNode(char nValue);
extern Node *etFirst=NULL;
extern Node *etRear=NULL;
extern Node *etNow=NULL;
extern Node *CreatNode_f(char nValue);
extern Node *CreatEtNode(int nValue);

void KeyLeft(void)
{Node *strpTemp;
 int n,i;
 strpTemp=strpNow;
 if(strpNow==NULL)
 return;
 else{
 if(wherex()==1&&wherey()==1)
 {scrdownroll(1,1,1,79,24);
  if(strpTemp->nData==13)
  {strpTemp=strpTemp->strpPre;
   n=etNow->nData;
   gotoxy(n,1);
   etNow=etNow->strpPre;
   for(i=n-1;i>=1;i--)
   {gotoxy(i,1);
    cprintf("%c",strpTemp->nData);
    strpTemp=strpTemp->strpPre;}
   gotoxy(n,1);
   strpNow=strpNow->strpPre;
   return;}
  else
  {for(i=79;i>=1;i--)
   {gotoxy(i,1);
    cprintf("%c",strpTemp->nData);
    strpTemp=strpTemp->strpPre;}
   gotoxy(79,1);
   strpNow=strpNow->strpPre;
   return;
   }
  }
 else
 {if(wherex()==1)
  {
   if(strpTemp->nData==13)
   {n=etNow->nData;
    gotoxy(n,wherey()-1);
    etNow=etNow->strpPre;}
   else
    gotoxy(79,wherey()-1);
   strpNow=strpNow->strpPre;
   return;
   }
  else
  {gotoxy(wherex()-1,wherey());
   strpNow=strpNow->strpPre;
   return;}
  }}
}

void KeyRight(void)
{Node *strpTemp;
 char buf1[79*1*2];
 if(strpNow==strpRear)
 return;
 else
 {if(strpNow==NULL)
  strpNow=strpFirst;
  else
   strpNow=strpNow->strpNext;
  strpTemp=strpNow;
 if(wherey()==24)
  {if(strpTemp->nData==13)
    {if(etNow==NULL)
      etNow=etFirst;
     else
      etNow=etNow->strpNext;
     scruproll(1,1,1,79,24);
     gotoxy(1,24);
     strpTemp=strpTemp->strpNext;
     while(wherex()!=79)
     {if(strpTemp==NULL)
      return;
      if(strpTemp->nData==13)
      {gotoxy(1,24);
       return;}
      cprintf("%c",strpTemp->nData);
      strpTemp=strpTemp->strpNext;
     }
     if(wherex()==79)
     {if(strpTemp==NULL)
      return;
      if(strpTemp->nData==13)
      {gotoxy(1,24);
       return;}
      gettext(2,2,80,2,buf1);
      cprintf("%c",strpTemp->nData);
      scrdownroll(1,1,1,79,24);
      puttext(2,2,80,2,buf1);
      gotoxy(1,24);
      return;
     }
     return;
    }
   else
   {if(wherex()==79)
     {cprintf("%c",strpTemp->nData);
      while(wherex()!=79)
      {if(strpTemp==NULL)
       return;
       if(strpTemp->nData==13)
       {gotoxy(1,24);
        return;}
       cprintf("%c",strpTemp->nData);
       strpTemp=strpTemp->strpNext;
       }
      if(wherex()==79)
      {if(strpTemp==NULL)
       return;
       if(strpTemp->nData==13)
       {gotoxy(1,24);
        return;}
       gettext(2,2,80,2,buf1);
       cprintf("%c",strpTemp->nData);
       scrdownroll(1,1,1,79,24);
       puttext(2,2,80,2,buf1);
       gotoxy(1,24);
       return;
      }
      return;
     }
    else
     {gotoxy(wherex()+1,24);
      return;}
   }
  }
 else
  {if(strpTemp->nData==13)
      {cprintf("\n%c",strpTemp->nData);
       if(etNow==NULL)
       etNow=etFirst;
       else
       etNow=etNow->strpNext;
       return;}
   if(wherex()==79)
    {gotoxy(1,wherey()+1);
     return;}
   else
    {gotoxy(wherex()+1,wherey());
     return;}
   }
   }
}

void KeyBS(void)
{Node *strpTemp,*strpTemp1,*strpTemp2,*strpTemp3,*strpTemp4;
 int m,n,i,t,x,y;
 char buf1[1*79*2];
 strpTemp2=strpNow;
 if(strpNow==NULL)
 return;
 else
 { if(strpNow==strpRear)
   {strpTemp=strpNow;
    strpNow=strpNow->strpPre;
    strpNow->strpNext=NULL;
    strpRear=strpNow;
    }
   else if(strpNow==strpFirst)
   {strpTemp=strpNow;
    strpFirst=strpNow->strpNext;
    strpFirst->strpPre=NULL;
    strpNow=NULL;
    }
   else
   {strpTemp=strpNow;
    strpTemp1=strpNow->strpNext;
    strpNow=strpTemp->strpPre;
    strpNow->strpNext=strpTemp1;
    strpTemp1->strpPre=strpNow;
    }
    strpTemp3=strpNow;
    strpTemp4=strpNow->strpNext;
  if(wherex()==1&&wherey()==1)
  {scrdownroll(1,1,1,79,24);
   if(strpTemp2->nData==13)
   { if(etNow==etRear)
     {strpTemp=etNow;
      etNow=etNow->strpPre;
      etNow->strpNext=NULL;
      etRear=etNow;
      }
     else if(etNow==etFirst)
     {strpTemp=etNow;
      etFirst=etNow->strpNext;
      etFirst->strpPre=NULL;
      etNow=NULL;
      }
     else
     {strpTemp=etNow;
      strpTemp1=etNow->strpNext;
      etNow=strpTemp->strpPre;
      etNow->strpNext=strpTemp1;
      strpTemp1->strpPre=etNow;}
     n=strpTemp->nData;
     gotoxy(n,1);
     for(i=n-1;i>=1;i--)
     {gotoxy(i,1);
      cprintf("%c",strpTemp3->nData);
      strpTemp3=strpTemp3->strpPre;}
     gotoxy(n,1);
     while((!(wherex()==79&&wherey()==24))&&strpTemp4!=NULL)
     {if(strpTemp4->nData!=13)
       cprintf("%c",strpTemp4->nData);
      else
       cprintf("\n%c",strpTemp4->nData);
      strpTemp4=strpTemp4->strpNext;}
     if(strpTemp4==NULL)
     {clreol();
      y=wherey();
      if(y!=24)
      {window(2,y+2,80,25);
       clrscr();
       window(2,2,80,25);}
       gotoxy(n,1);
      }
      if(wherex()==79&&wherey()==24)
      {gettext(2,2,80,2,buf1);
       if(strpTemp4->nData!=13)
        cprintf("%c",strpTemp4->nData);
       else
        cprintf("\n%c",strpTemp4->nData);
       scrdownroll(1,1,1,79,24);
       puttext(2,2,80,2,buf1);
       gotoxy(n,1);}
      return;
    }
    else
    {for(i=78;i>=1;i--)
     {gotoxy(i,1);
      cprintf("%c",strpTemp3->nData);
      strpTemp3=strpTemp3->strpPre;}
     gotoxy(79,1);
     while((!(wherex()==79&&wherey()==24))&&strpTemp4!=NULL)
     {if(strpTemp4->nData!=13)
       cprintf("%c",strpTemp4->nData);
      else
       cprintf("\n%c",strpTemp4->nData);
      strpTemp4=strpTemp4->strpNext;}
     if(strpTemp4==NULL)
     {clreol();
      y=wherey();
      if(y!=24)
      {window(2,y+2,80,25);
       clrscr();
       window(2,2,80,25);}
       gotoxy(79,1);
      }
      if(wherex()==79&&wherey()==24)
      {gettext(2,2,80,2,buf1);
       if(strpTemp4->nData!=13)
        cprintf("%c",strpTemp4->nData);
       else
        cprintf("\n%c",strpTemp4->nData);
       scrdownroll(1,1,1,79,24);
       puttext(2,2,80,2,buf1);
       gotoxy(79,1);}
      return;
     }
    }
   else
   {if(wherex()==1)
    {if(strpTemp2->nData==13)
     {if(etNow==etRear)
      {strpTemp=etNow;
       etNow=etNow->strpPre;
       etNow->strpNext=NULL;
       etRear=etNow;
       }
      else if(etNow==etFirst)
      {strpTemp=etNow;
       etFirst=etNow->strpNext;
       etFirst->strpPre=NULL;
       etNow=NULL;
       }
      else
      {strpTemp=etNow;
       strpTemp1=etNow->strpNext;
       etNow=strpTemp->strpPre;
       etNow->strpNext=strpTemp1;
       strpTemp1->strpPre=etNow;}
      t=wherey()-1;
      n=strpTemp->nData;
      gotoxy(n,t);
      while((!(wherex()==79&&wherey()==24))&&strpTemp4!=NULL)
      {if(strpTemp4->nData!=13)
        cprintf("%c",strpTemp4->nData);
       else
        cprintf("\n%c",strpTemp4->nData);
       strpTemp4=strpTemp4->strpNext;}
      if(strpTemp4==NULL)
      {clreol();
       y=wherey();
       if(y!=24)
       {window(2,y+2,80,25);
        clrscr();
        window(2,2,80,25);}
        gotoxy(n,t);
       }
      if(wherex()==79&&wherey()==24)
       {gettext(2,2,80,2,buf1);
        if(strpTemp4->nData!=13)
         cprintf("%c",strpTemp4->nData);
        else
         cprintf("\n%c",strpTemp4->nData);
        scrdownroll(1,1,1,79,24);
        puttext(2,2,80,2,buf1);
        gotoxy(n,t);}
       }
      else
       {t=wherey()-1;
        gotoxy(79,t);
        while((!(wherex()==79&&wherey()==24))&&strpTemp4!=NULL)
        {if(strpTemp4->nData!=13)
          cprintf("%c",strpTemp4->nData);
         else
          cprintf("\n%c",strpTemp4->nData);
         strpTemp4=strpTemp4->strpNext;}
        if(strpTemp4==NULL)
        {clreol();
         y=wherey();
         if(y!=24)
         {window(2,y+2,80,25);
          clrscr();
          window(2,2,80,25);}
          gotoxy(79,t);
         }
        if(wherex()==79&&wherey()==24)
         {gettext(2,2,80,2,buf1);
          if(strpTemp4->nData!=13)
           cprintf("%c",strpTemp4->nData);
          else
           cprintf("\n%c",strpTemp4->nData);
          scrdownroll(1,1,1,79,24);
          puttext(2,2,80,2,buf1);
          gotoxy(79,t);}
        }
      }
     else
      {m=wherex();
       n=wherey();
       gotoxy(m-1,n);
       while((!(wherex()==79&&wherey()==24))&&strpTemp4!=NULL)
        {if(strpTemp4->nData!=13)
          cprintf("%c",strpTemp4->nData);
         else
          cprintf("\n%c",strpTemp4->nData);
         strpTemp4=strpTemp4->strpNext;}
        if(strpTemp4==NULL)
        {clreol();
         y=wherey();
         if(y!=24)
         {window(2,y+2,80,25);
          clrscr();
          window(2,2,80,25);}
          gotoxy(m-1,n);
         }
        if(wherex()==79&&wherey()==24)
         {gettext(2,2,80,2,buf1);
          if(strpTemp4->nData!=13)
           cprintf("%c",strpTemp4->nData);
          else
           cprintf("\n%c",strpTemp4->nData);
          scrdownroll(1,1,1,79,24);
          puttext(2,2,80,2,buf1);
          gotoxy(m-1,n);}
         }
     }
  }
 return;
}
